name: Run Python Tests and Pre-Commit Hooks

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python 3.10
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'

          - name: Install uv
            uses: astral-sh/setup-uv@v3
            with:
              version: "0.4.15"

          - name: Install project
            run: uv sync --all-extras --dev

          - name: Run pre-commit hooks
            run: uvx --with pre-commit pre-commit run --all-files

          - name: Run tests
            run: uv run python -m unittest discover
